syntax = "proto3";

import "entity/method_options/method_options.proto";
import "entity/player.proto";

package app.playerlogin;

option csharp_namespace = "App.Protobuf.PlayerLogin";

message PlayerLoginRequest {
	string sdkUid = 1;
	string sdkAccessToken = 2;
	uint32 platform = 3;
	string deviceModel = 4;
	string operatingSystem = 5;
	string clientVersion = 6;
	PlayerUuid uuid = 7;
	string clientPackage = 8;
	string initial_data_group = 9;
	uint32 globalChannelId = 10;
	uint32 brandId = 11;
	uint32 areaId = 12;
	string idToken = 13;
}

message PlayerUuid {
	string adId = 1;
	string identifier = 2;
}

message PlayerLoginResponse {
	.entity.PlayerCredential credential = 1;
	string cpServerId = 2;
	string cpServerName = 3;
	uint32 isNewUser = 4;
}

message PlayerPreLoginResponse {
	bool isAccountCreated = 1;
}

message GetServerListRequest {
}

message ServerInfo {
	string name = 1;
	string cdnRoot = 2;
	string apiServerRoot = 3;
	string chatServerRoot = 4;
	string atServerRoot = 5;
	string liveServer = 6;
	string displayName = 7;
	string areaID = 8;
	string ageIconSpriteName = 9;
}

message GetServerListResponse {
	repeated ServerInfo servers = 1;
}

service PlayerLoginService {
	rpc PlayerLogin (.app.playerlogin.PlayerLoginRequest) returns (.app.playerlogin.PlayerLoginResponse) {
		option (entity.method_options.skip_authentication) = true;
	}

	rpc PlayerPreLogin (.app.playerlogin.PlayerLoginRequest) returns (.app.playerlogin.PlayerPreLoginResponse) {
		option (entity.method_options.skip_authentication) = true;
	}

	rpc GetServerList (.app.playerlogin.GetServerListRequest) returns (.app.playerlogin.GetServerListResponse) {
		option (entity.method_options.skip_authentication) = true;
	}
}
